name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Greeting
        run: echo "${{ env.GREETING }} Welcome to GitHub Actions."


