name: Example Workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    env:
      GREETING: "Hello"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Greeting
        run: echo "${{ env.GREETING }} Welcome to GitHub Actions."


